In [4]:
import numpy as np

In [22]:
import pandas as pd

###for arithmetic operations

In [40]:
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [41]:
2**a

array([ 2,  4,  8, 16], dtype=int32)

In [42]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [43]:
a * b

array([2., 4., 6., 8.])

In [45]:
j = np.arange(5)
j

array([0, 1, 2, 3, 4])

In [46]:
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

In [47]:
a = np.arange(10000)
%timeit a + 1

26.7 µs ± 3.37 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [48]:
l = range(10000)
%timeit [i+1 for i in l]

2.65 ms ± 241 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#Array multiplications

In [50]:
c = np.ones((3, 3))
c * c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
###for comparison

In [51]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [52]:
a > b

array([False, False,  True, False])

In [53]:
a >= b

array([False,  True,  True,  True])

In [ ]:
####for array comparisons

In [54]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
np.logical_or(a, b)

array([ True,  True,  True, False])

In [55]:
np.logical_and(a, b)

array([ True, False, False, False])

In [63]:
a = np.arange(5)
j = np.sin(a)

g = np.log(a)

y = np.exp(a)

C:\Users\taofiqueb\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


In [64]:
j

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [65]:
g

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [66]:
y

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
#Transposition

In [75]:
a = np.triu(np.ones((3, 3)), 1)   # see help(np.triu)
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [76]:
a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [77]:
#Computing sums
x = np.array([1, 2, 3, 4])

In [78]:
x

array([1, 2, 3, 4])

In [79]:
np.sum(x)

10

In [80]:
x.sum()

10

In [81]:
x = np.array([[1, 1], [2, 2]]) #sum by row and column

In [82]:
x

array([[1, 1],
       [2, 2]])

In [83]:
x.sum(axis=0)   # columns (first dimension)

array([3, 3])

In [84]:
x[:, 0].sum(), x[:, 1].sum()

(3, 3)

In [85]:
x.sum(axis=1)   # rows (second dimension)

array([2, 4])

In [86]:
x[0, :].sum(), x[1, :].sum()

(2, 4)

In [87]:
x = np.random.rand(2,2,2)

In [88]:
x

array([[[0.08974017, 0.97712736],
        [0.60019903, 0.99632571]],

       [[0.09419377, 0.98409141],
        [0.25148919, 0.09660798]]])

In [89]:
x.sum(axis=2)[0,1]

1.5965247363304629

In [91]:
x = np.array([1, 3, 2])
x

array([1, 3, 2])

In [93]:
x.min()

1

In [94]:
x.max()

3

In [95]:
x.argmin()  # index of minimum

0

In [96]:
x.argmax()  # index of maximum

1

In [97]:
np.all([True, True, False])

False

In [98]:
np.any([True, True, False])

True

In [100]:
a = np.zeros((100, 100))
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [101]:
np.any(a != 0)

False

In [102]:
np.all(a == a)

True

In [104]:
a = np.array([1, 2, 3, 2])
a

array([1, 2, 3, 2])

In [106]:
b = np.array([2, 2, 3, 2])
b

array([2, 2, 3, 2])

In [107]:
c = np.array([6, 4, 4, 5])
c

array([6, 4, 4, 5])

In [108]:
((a <= b) & (b <= c)).all()

True

In [109]:
x = np.array([1, 2, 3, 1])
x

array([1, 2, 3, 1])

In [111]:
x.mean()

1.75

In [112]:
np.median(x)

1.5

In [113]:
y = np.array([[1, 2, 3], [5, 6, 1]])
y

array([[1, 2, 3],
       [5, 6, 1]])

In [114]:
np.median(y, axis=-1) # last axis

array([2., 5.])

In [115]:
x.std()          # full population standard dev.

0.82915619758885