My name is Raji Bamidele
I live at Oloko Apata

In [13]:
a=1
b=2
a>a

False

In [14]:
b>a

True

In [15]:
a<0

False

In [1]:
x=5
x

5

In [2]:
x-2

3

In [5]:
x+3

8

In [6]:
x=10
x*5

50

In [7]:
x^5

15

In [8]:
y=12
x*y

120

In [10]:
2*x**2

200

In [11]:
x%2

0

In [12]:
x%3

1

In [13]:
x/5

2.0

In [15]:
x%7

3

In [16]:
str((1,2,3))

'(1, 2, 3)'

In [18]:
str((1,2,3,4))

'(1, 2, 3, 4)'

In [19]:
bool("True,False")

True

In [20]:
bool("False,False")

True

In [21]:
bool("True,True")

True

In [22]:
bool("False,True")

True

In [24]:
("True","False")

('True', 'False')

In [25]:
type("True")

str

In [26]:
type(True)

bool

In [28]:
a=bool(("True","False")) #this is used to convert strings to boolean

In [30]:
type(a)

bool

In [3]:
help(float)

Help on class float in module builtins:

class float(object)
 |  float(x=0, /)
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __int__(self, /)
 |      int(sel

In [4]:
a= "is"
b="nice"
my_list = ['my', 'list', a, b]

In [5]:
my_list

['my', 'list', 'is', 'nice']

In [6]:
my_rajja = [[2,4,6,8], [10,12,14,16]]
my_rajja
 

[[2, 4, 6, 8], [10, 12, 14, 16]]

In [9]:
a=1
d=2
f=4
g=6
t=12
a=14
s=7
owojori=[[a,d,f,g,t],[1,2,3,5],[1,a,s,5],[1,5,7,8,9]]
owojori

[[14, 2, 4, 6, 12], [1, 2, 3, 5], [1, 14, 7, 5], [1, 5, 7, 8, 9]]

In [10]:
adesina=[["ade","is","a","scientist"],[1,"for",2,"yes"],[1,5,7]] #this is used for list of lists
adesina

[['ade', 'is', 'a', 'scientist'], [1, 'for', 2, 'yes'], [1, 5, 7]]

In [11]:
print(adesina)

[['ade', 'is', 'a', 'scientist'], [1, 'for', 2, 'yes'], [1, 5, 7]]


In [12]:
my_list[0]

'my'

In [13]:
my_list[2]

'is'

In [15]:
my_list[-1]

'nice'

In [16]:
my_list[-2]

'is'

In [17]:
adesina[0]

['ade', 'is', 'a', 'scientist']

In [18]:
adesina[-1]

[1, 5, 7]

In [19]:
adesina[2]

[1, 5, 7]

In [20]:
adesina[1]

[1, 'for', 2, 'yes']

In [21]:
adesina[1][1]

'for'

In [22]:
adesina[1][3]

'yes'

In [24]:
adesina[1:3] #it means we are indexing from 1 to 2 bcos 3 will not be inclusive.

[[1, 'for', 2, 'yes'], [1, 5, 7]]

In [27]:
adesina[:2] #here we are indexing from the starting point to 2, it will terminate at 1 i.e. 0 and 1

[['ade', 'is', 'a', 'scientist'], [1, 'for', 2, 'yes']]

In [28]:
adesina[:3] #here we are indexing from the starting point to 3. note that even with the 3, it will terminate at 2 i.e. 0,1,2

[['ade', 'is', 'a', 'scientist'], [1, 'for', 2, 'yes'], [1, 5, 7]]

In [29]:
adesina[:] #if u want to list all the elements in the list

[['ade', 'is', 'a', 'scientist'], [1, 'for', 2, 'yes'], [1, 5, 7]]

In [76]:
#list methods
femi=[1,2,3,4,5,6,7,8,9,10]
femi

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [77]:
femi.index(10) #what index is 10? Answer: it is index 9

9

In [78]:
femi.index(5) #what index is 5? answer: it is index 4

4

In [79]:
femi.index(7)

6

In [80]:
femi.count(5) #this is used to count the number of 5's we have in femi which is just 1

1

In [81]:
sule=[1,2,3,4,5,6,5,5,5,7,8,9,10] # this is used to count the number of 5's we're having which is 4
sule.count(5)

4

In [82]:
femi.append(11) # this is used to append 11 to the list i.e. to update the list with 11

In [83]:
femi

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [84]:
#femi.append([12,13])

In [85]:
femi.extend([12,13]) #extend is used to add more than one value
femi

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [86]:
del(femi[:2])

In [87]:
femi

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [88]:
femi.pop(-1) # this is used to remove the last value in the list

13

In [89]:
femi

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [90]:
femi.extend([13,14])

In [91]:
femi

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [92]:
femi.pop(-1)

14

In [93]:
femi

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [94]:
femi.pop(5)
femi

[3, 4, 5, 6, 7, 9, 10, 11, 12, 13]

In [96]:
femi.sort() # this is used to sort from ascending order to descending order
femi

[3, 4, 5, 6, 7, 9, 10, 11, 12, 13]

In [98]:
femi.extend([8,19])
femi

[3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 8, 19]

In [99]:
femi.pop(-1)
femi

[3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 8]

In [100]:
femi.sort()
femi

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [101]:
femi.insert(11,14) #dis is used to insert by first specifying d index then d inserted value. use shift+tab 2c suggestn
femi

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [102]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [103]:
import numpy as np

In [110]:
femi_array = np.array(femi) #this is used to form list into array

In [111]:
femi_array

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [113]:
my_array = np.array([[3,5,7,8,9,11],[1,2,3,4,5,6],[2,4,6,8,10,12],[12,14,16,18,20,22]])

In [114]:
my_array # i.e. 6 rows and 4 columns

array([[ 3,  5,  7,  8,  9, 11],
       [ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [12, 14, 16, 18, 20, 22]])

In [115]:
my_array.shape

(4, 6)

In [116]:
femi_array.shape # it means we are having 12 rows and 1 columns

(12,)

In [117]:
my_array[:,0] # i.e. cutting the 1st column

array([ 3,  1,  2, 12])

In [118]:
my_array[:,1] # i.e cutting the 2nd column

array([ 5,  2,  4, 14])

In [119]:
my_array[:,2] # i.e cutting the 3rd column

array([ 7,  3,  6, 16])

In [120]:
my_array[:,3] # i.e cutting the 4th column

array([ 8,  4,  8, 18])

In [121]:
my_array[:,4]

array([ 9,  5, 10, 20])

In [122]:
my_array[0,:]

array([ 3,  5,  7,  8,  9, 11])

In [123]:
my_array[1,:]

array([1, 2, 3, 4, 5, 6])

In [124]:
my_array[2,:]

array([ 2,  4,  6,  8, 10, 12])

In [126]:
my_array[3,:]

array([12, 14, 16, 18, 20, 22])

In [145]:
my_array[3:4,4]

array([20])

In [146]:
np.mean(my_array)

8.666666666666666

In [147]:
np.median(my_array)

7.5

In [149]:
np.mean(my_array)

8.666666666666666

In [150]:
my_array[3:4,2:4]

array([[16, 18]])

In [151]:
practiz_array=np.array([[2,4,6,8],[9,3,8,7],[2,5,9,8],[1,6,2,3]])

In [152]:
practiz_array

array([[2, 4, 6, 8],
       [9, 3, 8, 7],
       [2, 5, 9, 8],
       [1, 6, 2, 3]])

In [153]:
practiz_array[1:3,2]

array([8, 9])

In [154]:
practiz_array[2:4,1:3]

array([[5, 9],
       [6, 2]])

In [155]:
practiz_array[2:3,1:3]

array([[5, 9]])

In [1]:
#All numpy methods/operations.
# State briefly at least one usefulness of each methods/operations


In [2]:
import numpy as np

In [10]:
def minus(x,y):
    try:
        return x - y
    except TypeError:
        return float(x) - float(y)


In [11]:
minus(5,2)

3

In [12]:
minus(8,1)

7

In [13]:
def add(a,b):
    try:
        return a + b
    except TypeError:
        return float(a) - float(b)

In [14]:
add(10,14)

24

In [15]:
add(200,234)

434

In [23]:
def multiply(x,y,z):
    return x*y*z

multiply(3,4,10) 

120

In [24]:
add_five=lambda x: x + 10
add_five(5)

15

In [25]:
add_five(8)

18

In [26]:
lambda x : x + 15

<function __main__.<lambda>(x)>

In [27]:
# for loop

In [31]:
for x in range(2,6):
    print('Numbers divided by two are:', x/2)

Numbers divided by two are: 1.0
Numbers divided by two are: 1.5
Numbers divided by two are: 2.0
Numbers divided by two are: 2.5


In [32]:
for y in range(3,17):
    print('Numbers divided by three are:', y/3)

Numbers divided by three are: 1.0
Numbers divided by three are: 1.3333333333333333
Numbers divided by three are: 1.6666666666666667
Numbers divided by three are: 2.0
Numbers divided by three are: 2.3333333333333335
Numbers divided by three are: 2.6666666666666665
Numbers divided by three are: 3.0
Numbers divided by three are: 3.3333333333333335
Numbers divided by three are: 3.6666666666666665
Numbers divided by three are: 4.0
Numbers divided by three are: 4.333333333333333
Numbers divided by three are: 4.666666666666667
Numbers divided by three are: 5.0
Numbers divided by three are: 5.333333333333333


In [37]:
for g in range(3,17):#for riounding up
    print('Numbers divided by three are:', round(g/3))

Numbers divided by three are: 1
Numbers divided by three are: 1
Numbers divided by three are: 2
Numbers divided by three are: 2
Numbers divided by three are: 2
Numbers divided by three are: 3
Numbers divided by three are: 3
Numbers divided by three are: 3
Numbers divided by three are: 4
Numbers divided by three are: 4
Numbers divided by three are: 4
Numbers divided by three are: 5
Numbers divided by three are: 5
Numbers divided by three are: 5


In [ ]:
#for i in [2,3,4,5]:

## PANDAS TUTORIAL

In [38]:
import pandas as pd

In [41]:
df = pd.read_csv('train_practise.csv')

In [42]:
df

ward  total_households  total_individuals     target  \
0     41601001: Ward 1        1674.45058         5888.20750  16.773757   
1     41601002: Ward 2        1736.99230         6735.33812  21.496661   
2     41601003: Ward 3        2403.57591         7273.04995  10.931425   
3     41601004: Ward 4        1740.78737         5734.49046  23.119257   
4     41601005: Ward 5        1730.51451         6657.23835  13.652252   
...                ...               ...                ...        ...   
2817  34503001: Ward 1        3261.68067        11551.56486   6.393480   
2818  34503002: Ward 2        1463.06432         7908.90411  15.668000   
2819  34503003: Ward 3        1395.18881         6242.37527  13.238795   
2820  34503004: Ward 4        1679.66964         8014.73089  17.639523   
2821  34503005: Ward 5        3008.38687         7899.36498  12.457680   

         dw_00     dw_01     dw_02     dw_03     dw_04     dw_05  ...  \
0     0.933841  0.000846  0.005490  0.000676  0.000000  0.001372  ...   
1     0.696940  0.001253  0.004402  0.000000  0.002301  0.001323  ...   
2     0.810545  0.004517  0.008891  0.003986  0.007735  0.000956  ...   
3     0.659914  0.000000  0.006129  0.000000  0.000813  0.037245  ...   
4     0.950575  0.000655  0.001473  0.000598  0.006999  0.000818  ...   
...        ...       ...       ...       ...       ...       ...  ...   
2817  0.874972  0.003146  0.017230  0.004735  0.048888  0.000654  ...   
2818  0.636235  0.002262  0.010433  0.000000  0.003030  0.000000  ...   
2819  0.855975  0.006601  0.061118  0.000812  0.003912  0.000812  ...   
2820  0.792552  0.004423  0.016099  0.000000  0.000674  0.000000  ...   
2821  0.254215  0.003310  0.121954  0.000000  0.001770  0.001023  ...   

         pw_03     pw_04     pw_05     pw_06  pw_07  pw_08  ADM4_PCODE  \
0     0.002848  0.007537  0.000000  0.012928      0      0   ZA4161001   
1     0.014566  0.057127  0.019092  0.004131      0      0   ZA4161002   
2     0.057560  0.010358  0.001421  0.040881      0      0   ZA4161003   
3     0.000000  0.000669  0.000000  0.005011      0      0   ZA4161004   
4     0.004859  0.001290  0.000673  0.017629      0      0   ZA4161005   
...        ...       ...       ...       ...    ...    ...         ...   
2817  0.000472  0.000472  0.000000  0.006203      0      0   ZA3453001   
2818  0.003030  0.000713  0.000000  0.008414      0      0   ZA3453002   
2819  0.002150  0.001458  0.000000  0.003670      0      0   ZA3453003   
2820  0.009235  0.007870  0.000000  0.004803      0      0   ZA3453004   
2821  0.003107  0.001636  0.000332  0.001770      0      0   ZA3453005   

            lat        lon        NL  
0    -29.682270  24.734743  0.292039  
1    -29.119311  24.757737  3.207775  
2    -29.142276  25.094093  0.000000  
3    -29.372052  24.942867  2.038778  
4    -29.409381  25.290165  0.000000  
...         ...        ...       ...  
2817 -27.675590  23.057920  9.118927  
2818 -27.591408  22.907161  1.697395  
2819 -27.952550  22.749698  2.792501  
2820 -27.913875  22.755314  2.793699  
2821 -27.741804  22.856933  0.001200  

[2822 rows x 63 columns]

In [43]:
df.dtypes #this is used to check data type

ward                  object
total_households     float64
total_individuals    float64
target               float64
dw_00                float64
                      ...   
pw_08                  int64
ADM4_PCODE            object
lat                  float64
lon                  float64
NL                   float64
Length: 63, dtype: object

In [45]:
df.shape #this is used to check the shape i.e. 63 columns and 2822 rows

(2822, 63)

In [46]:
df.head() # to check the portion of the data

ward  total_households  total_individuals     target     dw_00  \
0  41601001: Ward 1        1674.45058         5888.20750  16.773757  0.933841   
1  41601002: Ward 2        1736.99230         6735.33812  21.496661  0.696940   
2  41601003: Ward 3        2403.57591         7273.04995  10.931425  0.810545   
3  41601004: Ward 4        1740.78737         5734.49046  23.119257  0.659914   
4  41601005: Ward 5        1730.51451         6657.23835  13.652252  0.950575   

      dw_01     dw_02     dw_03     dw_04     dw_05  ...     pw_03     pw_04  \
0  0.000846  0.005490  0.000676  0.000000  0.001372  ...  0.002848  0.007537   
1  0.001253  0.004402  0.000000  0.002301  0.001323  ...  0.014566  0.057127   
2  0.004517  0.008891  0.003986  0.007735  0.000956  ...  0.057560  0.010358   
3  0.000000  0.006129  0.000000  0.000813  0.037245  ...  0.000000  0.000669   
4  0.000655  0.001473  0.000598  0.006999  0.000818  ...  0.004859  0.001290   

      pw_05     pw_06  pw_07  pw_08  ADM4_PCODE        lat        lon  \
0  0.000000  0.012928      0      0   ZA4161001 -29.682270  24.734743   
1  0.019092  0.004131      0      0   ZA4161002 -29.119311  24.757737   
2  0.001421  0.040881      0      0   ZA4161003 -29.142276  25.094093   
3  0.000000  0.005011      0      0   ZA4161004 -29.372052  24.942867   
4  0.000673  0.017629      0      0   ZA4161005 -29.409381  25.290165   

         NL  
0  0.292039  
1  3.207775  
2  0.000000  
3  2.038778  
4  0.000000  

[5 rows x 63 columns]

In [48]:
df.head(10) # this is used to check d protion of d data for 10 indent instead of d 5 for defaults

ward  total_households  total_individuals     target     dw_00  \
0  41601001: Ward 1        1674.45058         5888.20750  16.773757  0.933841   
1  41601002: Ward 2        1736.99230         6735.33812  21.496661  0.696940   
2  41601003: Ward 3        2403.57591         7273.04995  10.931425  0.810545   
3  41601004: Ward 4        1740.78737         5734.49046  23.119257  0.659914   
4  41601005: Ward 5        1730.51451         6657.23835  13.652252  0.950575   
5  41601006: Ward 6        1956.16888         6340.05782  25.249880  0.766832   
6  41602001: Ward 1        1966.40293         6230.77491  19.984585  0.908400   
7  41602002: Ward 2        2214.44168         6873.93123  16.511081  0.890079   
8  41602003: Ward 3        2022.95917         6736.49015  25.962117  0.912298   
9  41602004: Ward 4        1775.53323         5682.10110  21.744166  0.882665   

      dw_01     dw_02     dw_03     dw_04     dw_05  ...     pw_03     pw_04  \
0  0.000846  0.005490  0.000676  0.000000  0.001372  ...  0.002848  0.007537   
1  0.001253  0.004402  0.000000  0.002301  0.001323  ...  0.014566  0.057127   
2  0.004517  0.008891  0.003986  0.007735  0.000956  ...  0.057560  0.010358   
3  0.000000  0.006129  0.000000  0.000813  0.037245  ...  0.000000  0.000669   
4  0.000655  0.001473  0.000598  0.006999  0.000818  ...  0.004859  0.001290   
5  0.000579  0.005874  0.000000  0.000000  0.001448  ...  0.020771  0.002275   
6  0.006857  0.002941  0.000576  0.000720  0.001905  ...  0.003827  0.000509   
7  0.004549  0.002262  0.001151  0.000512  0.001805  ...  0.006364  0.001279   
8  0.002799  0.003688  0.000560  0.001260  0.000560  ...  0.006109  0.001276   
9  0.005227  0.009128  0.000000  0.003687  0.002839  ...  0.002644  0.000000   

      pw_05     pw_06  pw_07  pw_08  ADM4_PCODE        lat        lon  \
0  0.000000  0.012928      0      0   ZA4161001 -29.682270  24.734743   
1  0.019092  0.004131      0      0   ZA4161002 -29.119311  24.757737   
2  0.001421  0.040881      0      0   ZA4161003 -29.142276  25.094093   
3  0.000000  0.005011      0      0   ZA4161004 -29.372052  24.942867   
4  0.000673  0.017629      0      0   ZA4161005 -29.409381  25.290165   
5  0.024184  0.039423      0      0   ZA4161006 -29.126870  25.410360   
6  0.002542  0.020192      0      0   ZA4162001 -29.640860  26.091774   
7  0.000526  0.025246      0      0   ZA4162002 -30.029163  25.917164   
8  0.000000  0.008791      0      0   ZA4162003 -30.462176  26.133170   
9  0.000583  0.002073      0      0   ZA4162004 -30.420421  25.351630   

         NL  
0  0.292039  
1  3.207775  
2  0.000000  
3  2.038778  
4  0.000000  
5  1.464541  
6  0.821738  
7  0.000000  
8  0.000000  
9  0.000000  

[10 rows x 63 columns]

In [49]:
df.tail() # this is used to check d portion for tail with 5 as default

ward  total_households  total_individuals     target  \
2817  34503001: Ward 1        3261.68067        11551.56486   6.393480   
2818  34503002: Ward 2        1463.06432         7908.90411  15.668000   
2819  34503003: Ward 3        1395.18881         6242.37527  13.238795   
2820  34503004: Ward 4        1679.66964         8014.73089  17.639523   
2821  34503005: Ward 5        3008.38687         7899.36498  12.457680   

         dw_00     dw_01     dw_02     dw_03     dw_04     dw_05  ...  \
2817  0.874972  0.003146  0.017230  0.004735  0.048888  0.000654  ...   
2818  0.636235  0.002262  0.010433  0.000000  0.003030  0.000000  ...   
2819  0.855975  0.006601  0.061118  0.000812  0.003912  0.000812  ...   
2820  0.792552  0.004423  0.016099  0.000000  0.000674  0.000000  ...   
2821  0.254215  0.003310  0.121954  0.000000  0.001770  0.001023  ...   

         pw_03     pw_04     pw_05     pw_06  pw_07  pw_08  ADM4_PCODE  \
2817  0.000472  0.000472  0.000000  0.006203      0      0   ZA3453001   
2818  0.003030  0.000713  0.000000  0.008414      0      0   ZA3453002   
2819  0.002150  0.001458  0.000000  0.003670      0      0   ZA3453003   
2820  0.009235  0.007870  0.000000  0.004803      0      0   ZA3453004   
2821  0.003107  0.001636  0.000332  0.001770      0      0   ZA3453005   

            lat        lon        NL  
2817 -27.675590  23.057920  9.118927  
2818 -27.591408  22.907161  1.697395  
2819 -27.952550  22.749698  2.792501  
2820 -27.913875  22.755314  2.793699  
2821 -27.741804  22.856933  0.001200  

[5 rows x 63 columns]

In [50]:
df.tail(10) # this is used to check d portion for tail with 10

ward  total_households  total_individuals     target  \
2812   34502009: Ward 9         964.17366         3784.03630  30.593096   
2813  34502010: Ward 10        2915.45302        11176.02950  26.177120   
2814  34502011: Ward 11        1906.32047         6932.78429  21.439577   
2815  34502012: Ward 12        2797.24959        10294.11620  29.065233   
2816  34502013: Ward 13        1472.32727         6850.95588  15.288742   
2817   34503001: Ward 1        3261.68067        11551.56486   6.393480   
2818   34503002: Ward 2        1463.06432         7908.90411  15.668000   
2819   34503003: Ward 3        1395.18881         6242.37527  13.238795   
2820   34503004: Ward 4        1679.66964         8014.73089  17.639523   
2821   34503005: Ward 5        3008.38687         7899.36498  12.457680   

         dw_00     dw_01     dw_02     dw_03     dw_04     dw_05  ...  \
2812  0.702412  0.133519  0.002711  0.002122  0.000000  0.000000  ...   
2813  0.819065  0.082802  0.005098  0.000355  0.000369  0.000000  ...   
2814  0.831636  0.023670  0.006449  0.017388  0.000000  0.002779  ...   
2815  0.774917  0.081462  0.003547  0.000731  0.000447  0.001505  ...   
2816  0.766408  0.084505  0.008503  0.000703  0.000849  0.052410  ...   
2817  0.874972  0.003146  0.017230  0.004735  0.048888  0.000654  ...   
2818  0.636235  0.002262  0.010433  0.000000  0.003030  0.000000  ...   
2819  0.855975  0.006601  0.061118  0.000812  0.003912  0.000812  ...   
2820  0.792552  0.004423  0.016099  0.000000  0.000674  0.000000  ...   
2821  0.254215  0.003310  0.121954  0.000000  0.001770  0.001023  ...   

         pw_03     pw_04     pw_05     pw_06  pw_07  pw_08  ADM4_PCODE  \
2812  0.183343  0.079679  0.051607  0.007202      0      0   ZA3452009   
2813  0.204246  0.068946  0.047383  0.011443      0      0   ZA3452010   
2814  0.182566  0.104331  0.018653  0.005648      0      0   ZA3452011   
2815  0.188973  0.080660  0.030488  0.025442      0      0   ZA3452012   
2816  0.004380  0.000679  0.000000  0.035567      0      0   ZA3452013   
2817  0.000472  0.000472  0.000000  0.006203      0      0   ZA3453001   
2818  0.003030  0.000713  0.000000  0.008414      0      0   ZA3453002   
2819  0.002150  0.001458  0.000000  0.003670      0      0   ZA3453003   
2820  0.009235  0.007870  0.000000  0.004803      0      0   ZA3453004   
2821  0.003107  0.001636  0.000332  0.001770      0      0   ZA3453005   

            lat        lon        NL  
2812 -27.363593  23.356092  4.588434  
2813 -27.331466  23.320439  3.911402  
2814 -27.676921  23.600285  0.000000  
2815 -27.338311  23.437549  4.152665  
2816 -27.449982  23.468677  8.514053  
2817 -27.675590  23.057920  9.118927  
2818 -27.591408  22.907161  1.697395  
2819 -27.952550  22.749698  2.792501  
2820 -27.913875  22.755314  2.793699  
2821 -27.741804  22.856933  0.001200  

[10 rows x 63 columns]

In [56]:
df.column # for names of the features i.e the parameters used

AttributeError: 'DataFrame' object has no attribute 'column'

In [57]:
df.sample()# this is used to av a sample of d dataset

ward  total_households  total_individuals    target  \
2530  63805013: Ward 13        2307.62184        10019.23557  31.58919   

         dw_00     dw_01     dw_02     dw_03     dw_04     dw_05  ...  \
2530  0.528404  0.025557  0.000718  0.000895  0.001376  0.003212  ...   

         pw_03     pw_04     pw_05     pw_06  pw_07  pw_08  ADM4_PCODE  \
2530  0.037968  0.122974  0.003696  0.002288      0      0   ZA6385013   

            lat        lon        NL  
2530 -25.447974  25.965873  4.909219  

[1 rows x 63 columns]

In [59]:
df.sample(10) #this is used to get 10 samples of d dataset

ward  total_households  total_individuals     target  \
1976   83002005: Ward 5        1079.66212         3429.89282  16.568019   
123   41902017: Ward 17        2082.66034         7014.06621  32.974419   
2717   30802004: Ward 4        1679.78679         6375.27425  13.529019   
2793   34501005: Ward 5        1571.42021         5882.09376  28.736723   
1684  93404020: Ward 20        5259.35805        20508.04586  18.362104   
2258  83204028: Ward 28        1229.77397         6163.16424  25.912937   
1756  93504019: Ward 19        5344.24009        18258.71368  17.498036   
2531  63805014: Ward 14        1913.09118         8192.21446  23.138982   
2625  64003026: Ward 26        2625.18021         8787.31542  27.638122   
3      41601004: Ward 4        1740.78737         5734.49046  23.119257   

         dw_00     dw_01     dw_02     dw_03     dw_04     dw_05  ...  \
1976  0.759122  0.000000  0.002207  0.000000  0.000000  0.000000  ...   
123   0.685394  0.064652  0.007039  0.000544  0.000000  0.001768  ...   
2717  0.687726  0.017068  0.166203  0.002591  0.000946  0.000616  ...   
2793  0.558078  0.399758  0.004453  0.001336  0.000000  0.000000  ...   
1684  0.856955  0.013391  0.024140  0.000711  0.013451  0.002108  ...   
2258  0.971249  0.006180  0.002582  0.001716  0.000000  0.000000  ...   
1756  0.851087  0.001776  0.010658  0.001414  0.005065  0.001101  ...   
2531  0.683077  0.061290  0.001925  0.000563  0.000867  0.000000  ...   
2625  0.690227  0.000431  0.005767  0.000397  0.000431  0.049541  ...   
3     0.659914  0.000000  0.006129  0.000000  0.000813  0.037245  ...   

         pw_03     pw_04     pw_05     pw_06  pw_07  pw_08  ADM4_PCODE  \
1976  0.002016  0.178822  0.000000  0.000000      0      0   ZA8302005   
123   0.020114  0.004710  0.001715  0.041764      0      0   ZA4192017   
2717  0.002858  0.000916  0.000996  0.010074      0      0   ZA3082004   
2793  0.130228  0.042805  0.000658  0.024873      0      0   ZA3451005   
1684  0.030310  0.013977  0.002386  0.015633      0      0   ZA9344020   
2258  0.009489  0.004324  0.001707  0.042765      0      0   ZA8324028   
1756  0.001593  0.000000  0.000000  0.004438      0      0   ZA9354019   
2531  0.308050  0.023748  0.006698  0.143171      0      0   ZA6385014   
2625  0.000829  0.000000  0.000000  0.002557      0      0   ZA6403026   
3     0.000000  0.000669  0.000000  0.005011      0      0   ZA4161004   

            lat        lon         NL  
1976 -26.512113  30.008994  19.277495  
123  -28.335159  28.038604   0.940029  
2717 -28.836795  20.754887   0.071106  
2793 -27.091504  23.111762   0.107770  
1684 -23.280585  29.809275   0.637260  
2258 -25.715728  31.512999  13.594927  
1756 -23.909068  29.429012  40.467326  
2531 -25.492529  25.910439   4.385167  
2625 -26.978387  26.632397  22.237844  
3    -29.372052  24.942867   2.038778  

[10 rows x 63 columns]

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2822 entries, 0 to 2821
Data columns (total 63 columns):
ward                 2822 non-null object
total_households     2822 non-null float64
total_individuals    2822 non-null float64
target               2822 non-null float64
dw_00                2822 non-null float64
dw_01                2822 non-null float64
dw_02                2822 non-null float64
dw_03                2822 non-null float64
dw_04                2822 non-null float64
dw_05                2822 non-null float64
dw_06                2822 non-null float64
dw_07                2822 non-null float64
dw_08                2822 non-null float64
dw_09                2822 non-null float64
dw_10                2822 non-null float64
dw_11                2822 non-null float64
dw_12                2822 non-null int64
dw_13                2822 non-null int64
psa_00               2822 non-null float64
psa_01               2822 non-null float64
psa_02               2822 non-null flo

In [61]:
df.describe()

total_households  total_individuals       target        dw_00  \
count       2822.000000        2822.000000  2822.000000  2822.000000   
mean        3665.281214       12869.130053    24.507554     0.712196   
std         3266.364522        9696.690518    10.294387     0.214035   
min            1.000000         402.000000     0.000000     0.000000   
25%         1778.858235        7071.205695    16.751556     0.594212   
50%         2398.249935        9366.989680    24.156670     0.766841   
75%         3987.080563       14241.233015    32.226553     0.881708   
max        39684.942130       91716.746370    55.528423     0.994962   

             dw_01        dw_02        dw_03        dw_04        dw_05  \
count  2822.000000  2822.000000  2822.000000  2822.000000  2822.000000   
mean      0.092616     0.032043     0.006057     0.008665     0.006289   
std       0.182852     0.080253     0.019374     0.030697     0.024606   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.002895     0.002407     0.000000     0.000000     0.000000   
50%       0.010425     0.005762     0.000807     0.000607     0.000865   
75%       0.068209     0.027913     0.002538     0.002225     0.003027   
max       0.931490     0.951806     0.264239     0.392085     0.435912   

             dw_06  ...        pw_02        pw_03        pw_04        pw_05  \
count  2822.000000  ...  2822.000000  2822.000000  2822.000000  2822.000000   
mean      0.022375  ...     0.127555     0.041589     0.019655     0.011008   
std       0.037127  ...     0.156400     0.057331     0.032926     0.023672   
min       0.000000  ...     0.000000     0.000000     0.000000     0.000000   
25%       0.002716  ...     0.008673     0.002099     0.000715     0.000159   
50%       0.008639  ...     0.069065     0.016496     0.005164     0.001459   
75%       0.025218  ...     0.183384     0.058626     0.025055     0.009432   
max       0.412936  ...     1.000000     0.327393     0.306787     0.228261   

             pw_06   pw_07   pw_08          lat          lon           NL  
count  2822.000000  2822.0  2822.0  2822.000000  2822.000000  2822.000000  
mean      0.110818     0.0     0.0   -26.880740    28.666515    17.437560  
std       0.185401     0.0     0.0     2.021279     2.373809    18.958621  
min       0.000000     0.0     0.0   -32.490089    16.760022     0.000000  
25%       0.005217     0.0     0.0   -28.569019    27.707932     3.033397  
50%       0.025165     0.0     0.0   -26.549866    28.959679     9.205572  
75%       0.116638     0.0     0.0   -25.572130    30.441505    26.890531  
max       0.961523     0.0     0.0   -22.331267    32.858249    63.000000  

[8 rows x 61 columns]

In [60]:
df.corr()

total_households  total_individuals    target     dw_00  \
total_households           1.000000           0.959244 -0.374833 -0.226119   
total_individuals          0.959244           1.000000 -0.293827 -0.200350   
target                    -0.374833          -0.293827  1.000000  0.018461   
dw_00                     -0.226119          -0.200350  0.018461  1.000000   
dw_01                     -0.231304          -0.161183  0.458206 -0.614702   
...                             ...                ...       ...       ...   
pw_07                           NaN                NaN       NaN       NaN   
pw_08                           NaN                NaN       NaN       NaN   
lat                        0.063018           0.039653  0.120381  0.348089   
lon                        0.032249           0.104198  0.347088 -0.152692   
NL                         0.708701           0.684853 -0.514398 -0.133895   

                      dw_01     dw_02     dw_03     dw_04     dw_05     dw_06  \
total_households  -0.231304  0.222825  0.328743  0.314811  0.095374  0.284317   
total_individuals -0.161183  0.178921  0.255194  0.245253  0.109852  0.252280   
target             0.458206 -0.232727 -0.338137 -0.385533 -0.146357 -0.248573   
dw_00             -0.614702 -0.356335 -0.154956 -0.126421 -0.076181 -0.181262   
dw_01              1.000000  0.000617 -0.075112 -0.112250 -0.095776 -0.099431   
...                     ...       ...       ...       ...       ...       ...   
pw_07                   NaN       NaN       NaN       NaN       NaN       NaN   
pw_08                   NaN       NaN       NaN       NaN       NaN       NaN   
lat               -0.346198 -0.126910 -0.042252  0.009724 -0.093791  0.015586   
lon                0.349469  0.075945  0.028536 -0.028597 -0.135910 -0.052148   
NL                -0.338058  0.304287  0.321311  0.356428  0.180807  0.403524   

                   ...     pw_02     pw_03     pw_04     pw_05     pw_06  \
total_households   ... -0.140827 -0.149199 -0.121961 -0.110339 -0.228412   
total_individuals  ... -0.127982 -0.135562 -0.103966 -0.084651 -0.174518   
target             ...  0.442441  0.440941  0.389467  0.349653  0.470676   
dw_00              ... -0.064290 -0.079610 -0.059986 -0.038534 -0.297510   
dw_01              ...  0.222130  0.250931  0.202204  0.211378  0.600377   
...                ...       ...       ...       ...       ...       ...   
pw_07              ...       NaN       NaN       NaN       NaN       NaN   
pw_08              ...       NaN       NaN       NaN       NaN       NaN   
lat                ...  0.069398  0.114066  0.150117  0.114295 -0.029484   
lon                ...  0.077424  0.075826  0.136322  0.165803  0.325206   
NL                 ... -0.312929 -0.316221 -0.254358 -0.212811 -0.341468   

                   pw_07  pw_08       lat       lon        NL  
total_households     NaN    NaN  0.063018  0.032249  0.708701  
total_individuals    NaN    NaN  0.039653  0.104198  0.684853  
target               NaN    NaN  0.120381  0.347088 -0.514398  
dw_00                NaN    NaN  0.348089 -0.152692 -0.133895  
dw_01                NaN    NaN -0.346198  0.349469 -0.338058  
...                  ...    ...       ...       ...       ...  
pw_07                NaN    NaN       NaN       NaN       NaN  
pw_08                NaN    NaN       NaN       NaN       NaN  
lat                  NaN    NaN  1.000000  0.081587  0.049429  
lon                  NaN    NaN  0.081587  1.000000 -0.026927  
NL                   NaN    NaN  0.049429 -0.026927  1.000000  

[61 rows x 61 columns]

In [66]:
df['ward'].value_counts()

79700006: Ward 6     1
63802008: Ward 8     1
52901006: Ward 6     1
52902002: Ward 2     1
79700017: Ward 17    1
                    ..
93302025: Ward 25    1
49400026: Ward 26    1
52602006: Ward 6     1
41904005: Ward 5     1
52902015: Ward 15    1
Name: ward, Length: 2822, dtype: int64

In [67]:
type(df)# this is used to check d type of d data i.e it's a DataFrame

pandas.core.frame.DataFrame

In [69]:
type(df.ward)# this is used to check d type of d data i.e it's a Series

pandas.core.series.Series

In [70]:
df['total_households']

0       1674.45058
1       1736.99230
2       2403.57591
3       1740.78737
4       1730.51451
           ...    
2817    3261.68067
2818    1463.06432
2819    1395.18881
2820    1679.66964
2821    3008.38687
Name: total_households, Length: 2822, dtype: float64

In [71]:
df.pg_00.mean()# dis is used to calculate the mean of a series called pg_00

0.8621424599109138

In [72]:
df.pg_00.median

<bound method Series.median of 0       0.357455
1       0.698428
2       0.672452
3       0.728014
4       0.753491
          ...   
2817    0.387404
2818    0.619593
2819    0.551808
2820    0.366426
2821    0.903506
Name: pg_00, Length: 2822, dtype: float64>

In [74]:
df.pg_00.median()

0.98975152945

In [75]:
df.median()# d median for all

total_households     2398.249935
total_individuals    9366.989680
target                 24.156670
dw_00                   0.766841
dw_01                   0.010425
                        ...     
pw_07                   0.000000
pw_08                   0.000000
lat                   -26.549866
lon                    28.959679
NL                      9.205572
Length: 61, dtype: float64

In [76]:
df.skew()

total_households     2.715798
total_individuals    2.164591
target               0.109293
dw_00               -1.027741
dw_01                2.537747
                       ...   
pw_07                0.000000
pw_08                0.000000
lat                 -0.024309
lon                 -1.256801
NL                   1.149866
Length: 61, dtype: float64

In [77]:
df.groupby('ward')['lat'].value_counts()

ward               lat       
30601001: Ward 1   -28.603895    1
30601002: Ward 2   -28.769332    1
30601003: Ward 3   -29.227544    1
30601004: Ward 4   -29.369607    1
30602001: Ward 1   -29.268638    1
                                ..
94703027: Ward 27  -24.599760    1
94703028: Ward 28  -24.512810    1
94703029: Ward 29  -24.600257    1
94703030: Ward 30  -24.720679    1
94703031: Ward 31  -24.735269    1
Name: lat, Length: 2822, dtype: int64

In [78]:
pd.crosstab(df.ward,df.lat)

lat                -32.490089  -31.888645  -31.814231  -31.665732  -31.469394  \
ward                                                                            
30601001: Ward 1            0           0           0           0           0   
30601002: Ward 2            0           0           0           0           0   
30601003: Ward 3            0           0           0           0           0   
30601004: Ward 4            0           0           0           0           0   
30602001: Ward 1            0           0           0           0           0   
...                       ...         ...         ...         ...         ...   
94703027: Ward 27           0           0           0           0           0   
94703028: Ward 28           0           0           0           0           0   
94703029: Ward 29           0           0           0           0           0   
94703030: Ward 30           0           0           0           0           0   
94703031: Ward 31           0           0           0           0           0   

lat                -31.438364  -31.416559  -31.414525  -31.412418  -31.354671  \
ward                                                                            
30601001: Ward 1            0           0           0           0           0   
30601002: Ward 2            0           0           0           0           0   
30601003: Ward 3            0           0           0           0           0   
30601004: Ward 4            0           0           0           0           0   
30602001: Ward 1            0           0           0           0           0   
...                       ...         ...         ...         ...         ...   
94703027: Ward 27           0           0           0           0           0   
94703028: Ward 28           0           0           0           0           0   
94703029: Ward 29           0           0           0           0           0   
94703030: Ward 30           0           0           0           0           0   
94703031: Ward 31           0           0           0           0           0   

lat                ...  -22.713167  -22.708496  -22.672229  -22.605472  \
ward               ...                                                   
30601001: Ward 1   ...           0           0           0           0   
30601002: Ward 2   ...           0           0           0           0   
30601003: Ward 3   ...           0           0           0           0   
30601004: Ward 4   ...           0           0           0           0   
30602001: Ward 1   ...           0           0           0           0   
...                ...         ...         ...         ...         ...   
94703027: Ward 27  ...           0           0           0           0   
94703028: Ward 28  ...           0           0           0           0   
94703029: Ward 29  ...           0           0           0           0   
94703030: Ward 30  ...           0           0           0           0   
94703031: Ward 31  ...           0           0           0           0   

lat                -22.499977  -22.405593  -22.382846  -22.340825  -22.337394  \
ward                                                                            
30601001: Ward 1            0           0           0           0           0   
30601002: Ward 2            0           0           0           0           0   
30601003: Ward 3            0           0           0           0           0   
30601004: Ward 4            0           0           0           0           0   
30602001: Ward 1            0           0           0           0           0   
...                       ...         ...         ...         ...         ...   
94703027: Ward 27           0           0           0           0           0   
94703028: Ward 28           0           0           0           0           0   
94703029: Ward 29           0           0           0           0           0   
94703030: Ward 30           0         

In [83]:
dict_ass = {'A':[11,21,31],'B':[12,22,32],'C':[13,23,33]}
print('The values in variable A:',dict_ass['A'])
print('The values in variable B:',dict_ass['B'])
print('The values in variable C:',dict_ass['C'])

The values in variable A: [11, 21, 31]
The values in variable B: [12, 22, 32]
The values in variable C: [13, 23, 33]


In [86]:
dfff=pd.DataFrame(dict_ass)
dfff

A   B   C
0  11  12  13
1  21  22  23
2  31  32  33

In [88]:
dfff=pd.DataFrame(dict_ass,index=['ade','aisha','rajja']) #Adding index 'ade','aisha','rajja'
dfff

A   B   C
ade    11  12  13
aisha  21  22  23
rajja  31  32  33

In [84]:
dff = pd.DataFrame({'A':[11,21,31],'B':[12,22,32],'C':[13,23,33]},index=['ONE','TWO','THREE'])

In [85]:
dff

A   B   C
ONE    11  12  13
TWO    21  22  23
THREE  31  32  33

In [89]:
df.drop(['lat','lon'],axis=1, inplace=True)#axis=1 is used to delete lat$lon vertically while axis=0 is for horizontal

In [90]:
df.columns

Index(['ward', 'total_households', 'total_individuals', 'target', 'dw_00',
       'dw_01', 'dw_02', 'dw_03', 'dw_04', 'dw_05', 'dw_06', 'dw_07', 'dw_08',
       'dw_09', 'dw_10', 'dw_11', 'dw_12', 'dw_13', 'psa_00', 'psa_01',
       'psa_02', 'psa_03', 'psa_04', 'stv_00', 'stv_01', 'car_00', 'car_01',
       'lln_00', 'lln_01', 'lan_00', 'lan_01', 'lan_02', 'lan_03', 'lan_04',
       'lan_05', 'lan_06', 'lan_07', 'lan_08', 'lan_09', 'lan_10', 'lan_11',
       'lan_12', 'lan_13', 'lan_14', 'pg_00', 'pg_01', 'pg_02', 'pg_03',
       'pg_04', 'lgt_00', 'pw_00', 'pw_01', 'pw_02', 'pw_03', 'pw_04', 'pw_05',
       'pw_06', 'pw_07', 'pw_08', 'ADM4_PCODE', 'NL'],
      dtype='object')

In [94]:
df.drop('ADM4_PCODE', axis=1, inplace=True)

In [95]:
df.columns

Index(['ward', 'total_households', 'total_individuals', 'target', 'dw_00',
       'dw_01', 'dw_02', 'dw_03', 'dw_04', 'dw_05', 'dw_06', 'dw_07', 'dw_08',
       'dw_09', 'dw_10', 'dw_11', 'dw_12', 'dw_13', 'psa_00', 'psa_01',
       'psa_02', 'psa_03', 'psa_04', 'stv_00', 'stv_01', 'car_00', 'car_01',
       'lln_00', 'lln_01', 'lan_00', 'lan_01', 'lan_02', 'lan_03', 'lan_04',
       'lan_05', 'lan_06', 'lan_07', 'lan_08', 'lan_09', 'lan_10', 'lan_11',
       'lan_12', 'lan_13', 'lan_14', 'pg_00', 'pg_01', 'pg_02', 'pg_03',
       'pg_04', 'lgt_00', 'pw_00', 'pw_01', 'pw_02', 'pw_03', 'pw_04', 'pw_05',
       'pw_06', 'pw_07', 'pw_08', 'NL'],
      dtype='object')

In [ ]:
#All pandas methods/operations.
# State briefly at least one usefulness of each methods/operations.